export const MESSAGES = [
  "Anyone seen the enemy?",
  "Let's flank them from the left.",
  "I'm moving to the objective.",
  "Need backup, fast!",
  "Good job, team!",
  "Cover me while I reload.",
  "Enemy spotted at 12 o'clock.",
  "We need to hold this position!",
  "Take cover, incoming fire!",
  "I'm down, need a medic!",
  "Let's push them back!",
  "Don't forget to use your grenades.",

  "Watch your back, I'm coming for you.",
  "One shot, one kill. That's how we do it.",
  "Let's stick together and take them down.",
  "Reloading, cover me.",
  "You're going down, just like the rest.",
  "I see you, don't try to hide.",
  "Don't get too cocky, we can still lose.",
  "I'm low on health, need a medic ASAP.",
  "You can run, but you can't hide forever.",
  "I'm the king of this game, bow down to me."
];
export const USERNAMES = [
  "SniperAce",
  "BattleChamp",
  "ShadowStriker",
  "WarFalcon",
  "ThunderBlaze",
  "DeathWish",
  "GhostHunter",
  "CrimsonFury",
  "LoneWolf",
  "SavageQueen",
  "BlazeMaster",
  "SteelWarrior",
  "DarkKnight",
  "ViperStrike",
  "Frostbite",
  "StealthAssassin",
  "VenomousVixen",
  "PhoenixFlame",
  "DemonSlayer",
  "IronGiant",
  "SkyGuardian",
  "MysticMarauder",
  "ArcticWolf",
  "KnightRider",
  "ThunderBolt",
  "Blackout",
  "NightStalker",
  "ShadowWalker",
  "AssassinAce",
  "IceQueen",
  "BlazingBullet",
  "Warlord",
  "GunSlinger",
  "DemonHunter",
  "SteelSamurai",
  "CrimsonReaper",
  "NovaNinja",
  "ThunderStruck",
  "MysticMage",
  "FireFox",
  "ShadowSword",
  "HurricaneHawk",
  "ViciousVendetta",
  "IronWill",
  "DarkDragon",
  "BlazeBomber",
  "WolfWarrior",
  "MysticMuse",
  "SkySavior",
  "SavageSamurai",
  "PhoenixFire",
  "DeathDealer",
  "GhostGunner",
  "ShadowSniper",
  "FrostFang",
  "StealthSniper",
  "VenomousVampire",
  "CrimsonCobra",
  "LoneLancer",
  "ThunderThor",
  "BlackKnight",
  "NightNinja",
  "ShadowShooter",
  "AssassinArrow",
  "IceIcicle",
  "BlazeBlaster",
  "WarWhiz",
  "GunGeneral",
  "DemonDoom",
  "SteelSoldier",
  "CrimsonCrusader",
  "NovaNightmare",
  "ThunderTornado",
  "MysticMercenary",
  "FireFury",
  "ShadowSabre",
  "HurricaneHunter",
  "ViciousViking",
  "IronInferno",
  "DarkDevil",
  "BlazeBrawler",
  "WolfWanderer",
  "MysticMortal",
  "SkySpecter",
  "SavageSpartan",
  "PhoenixPhoenix",
  "DeathDefier",
  "GhostGambler",
  "ShadowSlayer",
  "FrostFreeze",
  "StealthSoldier",
  "VenomousVindicator",
  "CrimsonCrown",
  "LoneLoneWolf",
  "ThunderTiger",
  "BlackBlade",
  "NightNightmare",
  "ShadowSharpshooter",
  "AssassinAssailant",
  "IceInferno"
];
